<?xml version="1.0" encoding="UTF-8" standalone="yes"?><!DOCTYPE j8583-config[<!ELEMENT j8583-config ( header*, template*, parse* ) >

    <!ELEMENT header ( #PCDATA ) ><!ATTLIST header type NMTOKEN #REQUIRED ><!ATTLIST header ref NMTOKEN #IMPLIED >

    <!ELEMENT template ( field* ) ><!ATTLIST template type NMTOKEN #REQUIRED ><!ATTLIST template extends NMTOKEN #IMPLIED >

    <!ELEMENT parse ( field+ ) ><!ATTLIST parse type NMTOKEN #REQUIRED ><!ATTLIST parse extends NMTOKEN #IMPLIED >

    <!ELEMENT field ( #PCDATA|field )* ><!ATTLIST field num NMTOKEN #REQUIRED ><!ATTLIST field length NMTOKEN #IMPLIED ><!ATTLIST field type ( ALPHA | NUMERIC | AMOUNT | DATE10 | DATE4 | DATE_EXP | TIME | LLVAR | LLLVAR | BINARY | LLBIN | LLLBIN | exclude) #REQUIRED >]>

<j8583-config>
    <!-- These are the ISO headers to be prepended to the message types specified -->

    <header type="0200">ISO015000050</header>
    <header type="0210">ISO015000055</header>
    <header type="0400">ISO015000050</header>
    <header type="0410">ISO015000055</header>
    <header type="0800">ISO015000015</header>
    <header type="0810">ISO015000015</header>

    <parse type="0100">
        <field length="19" num="2" type="LLVAR" />
        <field length="6" num="3" type="ALPHA" />
        <field length="12" num="4" type="ALPHA" />
        <field length="12" num="5" type="ALPHA" />
        <field length="12" num="6" type="ALPHA" />
        <field length="10" num="7" type="ALPHA" />
        <field length="8" num="8" type="ALPHA" />
        <field length="8" num="9" type="ALPHA" />
        <field length="8" num="10" type="ALPHA" />
        <field length="6" num="11" type="ALPHA" />
        <field length="6" num="12" type="ALPHA" />
        <field length="4" num="13" type="ALPHA" />
        <field length="4" num="14" type="ALPHA" />
        <field length="6" num="15" type="ALPHA" />
        <field length="4" num="16" type="ALPHA" />
        <field length="4" num="17" type="ALPHA" />
        <field length="4" num="18" type="ALPHA" />
        <field length="3" num="19" type="ALPHA" />
        <field length="3" num="20" type="ALPHA" />
        <field length="3" num="21" type="ALPHA" />
        <field length="3" num="22" type="ALPHA" />
        <field length="3" num="23" type="ALPHA" />
        <field length="3" num="24" type="ALPHA" />
        <field length="2" num="25" type="ALPHA" />
        <field length="2" num="26" type="ALPHA" />
        <field length="1" num="27" type="ALPHA" />
        <field length="9" num="28" type="ALPHA" />
        <field length="9" num="29" type="ALPHA" />
        <field length="9" num="30" type="ALPHA" />
        <field length="9" num="31" type="ALPHA" />
        <field length="11" num="32" type="LLVAR" />
        <field length="11" num="33" type="LLVAR" />
        <field length="28" num="34" type="LLVAR" />
        <field length="37" num="35" type="LLVAR" />
        <field length="104" num="36" type="LLLVAR" />
        <field length="12" num="37" type="ALPHA" />
        <field length="6" num="38" type="ALPHA" />
        <field length="2" num="39" type="ALPHA" />
        <field length="3" num="40" type="ALPHA" />
        <field length="8" num="41" type="ALPHA" />
        <field length="15" num="42" type="ALPHA" />
        <field length="40" num="43" type="ALPHA" />
        <field length="25" num="44" type="LLVAR" />
        <field length="76" num="45" type="LLVAR" />
        <field length="999" num="46" type="LLLVAR" />
        <field length="999" num="47" type="LLLVAR" />
        <field length="999" num="48" type="LLLVAR" />
        <field length="3" num="49" type="ALPHA" />
        <field length="3" num="50" type="ALPHA" />
        <field length="3" num="51" type="ALPHA" />
        <field length="16" num="52" type="ALPHA" />
        <field length="96" num="53" type="ALPHA" />
        <field length="120" num="54" type="LLLVAR" />
        <field length="999" num="55" type="LLLVAR" />
        <field length="999" num="56" type="LLLVAR" />
        <field length="999" num="57" type="LLLVAR" />
        <field length="999" num="58" type="LLLVAR" />
        <field length="999" num="59" type="LLLVAR" />
        <field length="999" num="60" type="LLLVAR" />
        <field length="999" num="61" type="LLLVAR" />
        <field length="999" num="62" type="LLLVAR" />
        <field length="999" num="63" type="LLLVAR" />
        <field length="64" num="64" type="ALPHA" />
        <field length="42" num="90" type="ALPHA" />
        <field length="42" num="95" type="ALPHA" />
        <field length="28" num="102" type="LLVAR" />
        <field length="28" num="103" type="LLVAR" />
        <field length="15" num="123" type="LLLVAR" />
        <field length="64" num="128" type="ALPHA" />
    </parse>

    <parse type="0110">
        <field length="19" num="2" type="LLVAR" />
        <field length="6" num="3" type="ALPHA" />
        <field length="12" num="4" type="ALPHA" />
        <field length="12" num="5" type="ALPHA" />
        <field length="12" num="6" type="ALPHA" />
        <field length="10" num="7" type="ALPHA" />
        <field length="8" num="8" type="ALPHA" />
        <field length="8" num="9" type="ALPHA" />
        <field length="8" num="10" type="ALPHA" />
        <field length="6" num="11" type="ALPHA" />
        <field length="6" num="12" type="ALPHA" />
        <field length="4" num="13" type="ALPHA" />
        <field length="4" num="14" type="ALPHA" />
        <field length="6" num="15" type="ALPHA" />
        <field length="4" num="16" type="ALPHA" />
        <field length="4" num="17" type="ALPHA" />
        <field length="4" num="18" type="ALPHA" />
        <field length="3" num="19" type="ALPHA" />
        <field length="3" num="20" type="ALPHA" />
        <field length="3" num="21" type="ALPHA" />
        <field length="3" num="22" type="ALPHA" />
        <field length="3" num="23" type="ALPHA" />
        <field length="3" num="24" type="ALPHA" />
        <field length="2" num="25" type="ALPHA" />
        <field length="2" num="26" type="ALPHA" />
        <field length="1" num="27" type="ALPHA" />
        <field length="9" num="28" type="ALPHA" />
        <field length="9" num="29" type="ALPHA" />
        <field length="9" num="30" type="ALPHA" />
        <field length="9" num="31" type="ALPHA" />
        <field length="11" num="32" type="LLVAR" />
        <field length="11" num="33" type="LLVAR" />
        <field length="28" num="34" type="LLVAR" />
        <field length="37" num="35" type="LLVAR" />
        <field length="104" num="36" type="LLLVAR" />
        <field length="12" num="37" type="ALPHA" />
        <field length="6" num="38" type="ALPHA" />
        <field length="2" num="39" type="ALPHA" />
        <field length="3" num="40" type="ALPHA" />
        <field length="8" num="41" type="ALPHA" />
        <field length="15" num="42" type="ALPHA" />
        <field length="40" num="43" type="ALPHA" />
        <field length="25" num="44" type="LLVAR" />
        <field length="76" num="45" type="LLVAR" />
        <field length="999" num="46" type="LLLVAR" />
        <field length="999" num="47" type="LLLVAR" />
        <field length="999" num="48" type="LLLVAR" />
        <field length="3" num="49" type="ALPHA" />
        <field length="3" num="50" type="ALPHA" />
        <field length="3" num="51" type="ALPHA" />
        <field length="16" num="52" type="ALPHA" />
        <field length="96" num="53" type="ALPHA" />
        <field length="120" num="54" type="LLLVAR" />
        <field length="999" num="55" type="LLLVAR" />
        <field length="999" num="56" type="LLLVAR" />
        <field length="999" num="57" type="LLLVAR" />
        <field length="999" num="58" type="LLLVAR" />
        <field length="999" num="59" type="LLLVAR" />
        <field length="999" num="60" type="LLLVAR" />
        <field length="999" num="61" type="LLLVAR" />
        <field length="999" num="62" type="LLLVAR" />
        <field length="999" num="63" type="LLLVAR" />
        <field length="64" num="64" type="ALPHA" />
        <field length="42" num="90" type="ALPHA" />
        <field length="42" num="95" type="ALPHA" />
        <field length="28" num="102" type="LLVAR" />
        <field length="28" num="103" type="LLVAR" />
        <field length="15" num="123" type="LLLVAR" />
        <field length="64" num="128" type="ALPHA" />
    </parse>

    <parse type="0200">
        <field length="19" num="2" type="LLVAR" />
        <field length="6" num="3" type="ALPHA" />
        <field length="12" num="4" type="ALPHA" />
        <field length="12" num="5" type="ALPHA" />
        <field length="12" num="6" type="ALPHA" />
        <field length="10" num="7" type="ALPHA" />
        <field length="8" num="8" type="ALPHA" />
        <field length="8" num="9" type="ALPHA" />
        <field length="8" num="10" type="ALPHA" />
        <field length="6" num="11" type="ALPHA" />
        <field length="6" num="12" type="ALPHA" />
        <field length="4" num="13" type="ALPHA" />
        <field length="4" num="14" type="ALPHA" />
        <field length="6" num="15" type="ALPHA" />
        <field length="4" num="16" type="ALPHA" />
        <field length="4" num="17" type="ALPHA" />
        <field length="4" num="18" type="ALPHA" />
        <field length="3" num="19" type="ALPHA" />
        <field length="3" num="20" type="ALPHA" />
        <field length="3" num="21" type="ALPHA" />
        <field length="3" num="22" type="ALPHA" />
        <field length="3" num="23" type="ALPHA" />
        <field length="3" num="24" type="ALPHA" />
        <field length="2" num="25" type="ALPHA" />
        <field length="2" num="26" type="ALPHA" />
        <field length="1" num="27" type="ALPHA" />
        <field length="9" num="28" type="ALPHA" />
        <field length="9" num="29" type="ALPHA" />
        <field length="9" num="30" type="ALPHA" />
        <field length="9" num="31" type="ALPHA" />
        <field length="11" num="32" type="LLVAR" />
        <field length="11" num="33" type="LLVAR" />
        <field length="28" num="34" type="LLVAR" />
        <field length="37" num="35" type="LLVAR" />
        <field length="104" num="36" type="LLLVAR" />
        <field length="12" num="37" type="ALPHA" />
        <field length="6" num="38" type="ALPHA" />
        <field length="2" num="39" type="ALPHA" />
        <field length="3" num="40" type="ALPHA" />
        <field length="8" num="41" type="ALPHA" />
        <field length="15" num="42" type="ALPHA" />
        <field length="40" num="43" type="ALPHA" />
        <field length="25" num="44" type="LLVAR" />
        <field length="76" num="45" type="LLVAR" />
        <field length="999" num="46" type="LLLVAR" />
        <field length="999" num="47" type="LLLVAR" />
        <field length="999" num="48" type="LLLVAR" />
        <field length="3" num="49" type="ALPHA" />
        <field length="3" num="50" type="ALPHA" />
        <field length="3" num="51" type="ALPHA" />
        <field length="16" num="52" type="ALPHA" />
        <field length="96" num="53" type="ALPHA" />
        <field length="120" num="54" type="LLLVAR" />
        <field length="999" num="55" type="LLLVAR" />
        <field length="999" num="56" type="LLLVAR" />
        <field length="999" num="57" type="LLLVAR" />
        <field length="999" num="58" type="LLLVAR" />
        <field length="999" num="59" type="LLLVAR" />
        <field length="999" num="60" type="LLLVAR" />
        <field length="999" num="61" type="LLLVAR" />
        <field length="999" num="62" type="LLLVAR" />
        <field length="999" num="63" type="LLLVAR" />
        <field length="64" num="64" type="ALPHA" />
        <field length="42" num="90" type="ALPHA" />
        <field length="42" num="95" type="ALPHA" />
        <field length="28" num="102" type="LLVAR" />
        <field length="28" num="103" type="LLVAR" />
        <field length="15" num="123" type="LLLVAR" />
        <field length="64" num="128" type="ALPHA" />
    </parse>

    <parse type="0210">
        <field length="19" num="2" type="LLVAR" />
        <field length="6" num="3" type="ALPHA" />
        <field length="12" num="4" type="ALPHA" />
        <field length="12" num="5" type="ALPHA" />
        <field length="12" num="6" type="ALPHA" />
        <field length="10" num="7" type="ALPHA" />
        <field length="8" num="8" type="ALPHA" />
        <field length="8" num="9" type="ALPHA" />
        <field length="8" num="10" type="ALPHA" />
        <field length="6" num="11" type="ALPHA" />
        <field length="6" num="12" type="ALPHA" />
        <field length="4" num="13" type="ALPHA" />
        <field length="4" num="14" type="ALPHA" />
        <field length="6" num="15" type="ALPHA" />
        <field length="4" num="16" type="ALPHA" />
        <field length="4" num="17" type="ALPHA" />
        <field length="4" num="18" type="ALPHA" />
        <field length="3" num="19" type="ALPHA" />
        <field length="3" num="20" type="ALPHA" />
        <field length="3" num="21" type="ALPHA" />
        <field length="3" num="22" type="ALPHA" />
        <field length="3" num="23" type="ALPHA" />
        <field length="3" num="24" type="ALPHA" />
        <field length="2" num="25" type="ALPHA" />
        <field length="2" num="26" type="ALPHA" />
        <field length="1" num="27" type="ALPHA" />
        <field length="9" num="28" type="ALPHA" />
        <field length="9" num="29" type="ALPHA" />
        <field length="9" num="30" type="ALPHA" />
        <field length="9" num="31" type="ALPHA" />
        <field length="11" num="32" type="LLVAR" />
        <field length="11" num="33" type="LLVAR" />
        <field length="28" num="34" type="LLVAR" />
        <field length="37" num="35" type="LLVAR" />
        <field length="104" num="36" type="LLLVAR" />
        <field length="12" num="37" type="ALPHA" />
        <field length="6" num="38" type="ALPHA" />
        <field length="2" num="39" type="ALPHA" />
        <field length="3" num="40" type="ALPHA" />
        <field length="8" num="41" type="ALPHA" />
        <field length="15" num="42" type="ALPHA" />
        <field length="40" num="43" type="ALPHA" />
        <field length="25" num="44" type="LLVAR" />
        <field length="76" num="45" type="LLVAR" />
        <field length="999" num="46" type="LLLVAR" />
        <field length="999" num="47" type="LLLVAR" />
        <field length="999" num="48" type="LLLVAR" />
        <field length="3" num="49" type="ALPHA" />
        <field length="3" num="50" type="ALPHA" />
        <field length="3" num="51" type="ALPHA" />
        <field length="16" num="52" type="ALPHA" />
        <field length="96" num="53" type="ALPHA" />
        <field length="120" num="54" type="LLLVAR" />
        <field length="999" num="55" type="LLLVAR" />
        <field length="999" num="56" type="LLLVAR" />
        <field length="999" num="57" type="LLLVAR" />
        <field length="999" num="58" type="LLLVAR" />
        <field length="999" num="59" type="LLLVAR" />
        <field length="999" num="60" type="LLLVAR" />
        <field length="999" num="61" type="LLLVAR" />
        <field length="999" num="62" type="LLLVAR" />
        <field length="999" num="63" type="LLLVAR" />
        <field length="64" num="64" type="ALPHA" />
        <field length="42" num="90" type="ALPHA" />
        <field length="42" num="95" type="ALPHA" />
        <field length="28" num="102" type="LLVAR" />
        <field length="28" num="103" type="LLVAR" />
        <field length="15" num="123" type="LLLVAR" />
        <field length="64" num="128" type="ALPHA" />
    </parse>

    <parse type="0420">
        <field length="19" num="2" type="LLVAR" />
        <field length="6" num="3" type="ALPHA" />
        <field length="12" num="4" type="ALPHA" />
        <field length="12" num="5" type="ALPHA" />
        <field length="12" num="6" type="ALPHA" />
        <field length="10" num="7" type="ALPHA" />
        <field length="8" num="8" type="ALPHA" />
        <field length="8" num="9" type="ALPHA" />
        <field length="8" num="10" type="ALPHA" />
        <field length="6" num="11" type="ALPHA" />
        <field length="6" num="12" type="ALPHA" />
        <field length="4" num="13" type="ALPHA" />
        <field length="4" num="14" type="ALPHA" />
        <field length="6" num="15" type="ALPHA" />
        <field length="4" num="16" type="ALPHA" />
        <field length="4" num="17" type="ALPHA" />
        <field length="4" num="18" type="ALPHA" />
        <field length="3" num="19" type="ALPHA" />
        <field length="3" num="20" type="ALPHA" />
        <field length="3" num="21" type="ALPHA" />
        <field length="3" num="22" type="ALPHA" />
        <field length="3" num="23" type="ALPHA" />
        <field length="3" num="24" type="ALPHA" />
        <field length="2" num="25" type="ALPHA" />
        <field length="2" num="26" type="ALPHA" />
        <field length="1" num="27" type="ALPHA" />
        <field length="9" num="28" type="ALPHA" />
        <field length="9" num="29" type="ALPHA" />
        <field length="9" num="30" type="ALPHA" />
        <field length="9" num="31" type="ALPHA" />
        <field length="11" num="32" type="LLVAR" />
        <field length="11" num="33" type="LLVAR" />
        <field length="28" num="34" type="LLVAR" />
        <field length="37" num="35" type="LLVAR" />
        <field length="104" num="36" type="LLLVAR" />
        <field length="12" num="37" type="ALPHA" />
        <field length="6" num="38" type="ALPHA" />
        <field length="2" num="39" type="ALPHA" />
        <field length="3" num="40" type="ALPHA" />
        <field length="8" num="41" type="ALPHA" />
        <field length="15" num="42" type="ALPHA" />
        <field length="40" num="43" type="ALPHA" />
        <field length="25" num="44" type="LLVAR" />
        <field length="76" num="45" type="LLVAR" />
        <field length="999" num="46" type="LLLVAR" />
        <field length="999" num="47" type="LLLVAR" />
        <field length="999" num="48" type="LLLVAR" />
        <field length="3" num="49" type="ALPHA" />
        <field length="3" num="50" type="ALPHA" />
        <field length="3" num="51" type="ALPHA" />
        <field length="16" num="52" type="ALPHA" />
        <field length="96" num="53" type="ALPHA" />
        <field length="120" num="54" type="LLLVAR" />
        <field length="999" num="55" type="LLLVAR" />
        <field length="999" num="56" type="LLLVAR" />
        <field length="999" num="57" type="LLLVAR" />
        <field length="999" num="58" type="LLLVAR" />
        <field length="999" num="59" type="LLLVAR" />
        <field length="999" num="60" type="LLLVAR" />
        <field length="999" num="61" type="LLLVAR" />
        <field length="999" num="62" type="LLLVAR" />
        <field length="999" num="63" type="LLLVAR" />
        <field length="64" num="64" type="ALPHA" />
        <field length="42" num="90" type="ALPHA" />
        <field length="42" num="95" type="ALPHA" />
        <field length="28" num="102" type="LLVAR" />
        <field length="28" num="103" type="LLVAR" />
        <field length="15" num="123" type="LLLVAR" />
        <field length="64" num="128" type="ALPHA" />
    </parse>

    <parse type="0421">
        <field length="19" num="2" type="LLVAR" />
        <field length="6" num="3" type="ALPHA" />
        <field length="12" num="4" type="ALPHA" />
        <field length="12" num="5" type="ALPHA" />
        <field length="12" num="6" type="ALPHA" />
        <field length="10" num="7" type="ALPHA" />
        <field length="8" num="8" type="ALPHA" />
        <field length="8" num="9" type="ALPHA" />
        <field length="8" num="10" type="ALPHA" />
        <field length="6" num="11" type="ALPHA" />
        <field length="6" num="12" type="ALPHA" />
        <field length="4" num="13" type="ALPHA" />
        <field length="4" num="14" type="ALPHA" />
        <field length="6" num="15" type="ALPHA" />
        <field length="4" num="16" type="ALPHA" />
        <field length="4" num="17" type="ALPHA" />
        <field length="4" num="18" type="ALPHA" />
        <field length="3" num="19" type="ALPHA" />
        <field length="3" num="20" type="ALPHA" />
        <field length="3" num="21" type="ALPHA" />
        <field length="3" num="22" type="ALPHA" />
        <field length="3" num="23" type="ALPHA" />
        <field length="3" num="24" type="ALPHA" />
        <field length="2" num="25" type="ALPHA" />
        <field length="2" num="26" type="ALPHA" />
        <field length="1" num="27" type="ALPHA" />
        <field length="9" num="28" type="ALPHA" />
        <field length="9" num="29" type="ALPHA" />
        <field length="9" num="30" type="ALPHA" />
        <field length="9" num="31" type="ALPHA" />
        <field length="11" num="32" type="LLVAR" />
        <field length="11" num="33" type="LLVAR" />
        <field length="28" num="34" type="LLVAR" />
        <field length="37" num="35" type="LLVAR" />
        <field length="104" num="36" type="LLLVAR" />
        <field length="12" num="37" type="ALPHA" />
        <field length="6" num="38" type="ALPHA" />
        <field length="2" num="39" type="ALPHA" />
        <field length="3" num="40" type="ALPHA" />
        <field length="8" num="41" type="ALPHA" />
        <field length="15" num="42" type="ALPHA" />
        <field length="40" num="43" type="ALPHA" />
        <field length="25" num="44" type="LLVAR" />
        <field length="76" num="45" type="LLVAR" />
        <field length="999" num="46" type="LLLVAR" />
        <field length="999" num="47" type="LLLVAR" />
        <field length="999" num="48" type="LLLVAR" />
        <field length="3" num="49" type="ALPHA" />
        <field length="3" num="50" type="ALPHA" />
        <field length="3" num="51" type="ALPHA" />
        <field length="16" num="52" type="ALPHA" />
        <field length="96" num="53" type="ALPHA" />
        <field length="120" num="54" type="LLLVAR" />
        <field length="999" num="55" type="LLLVAR" />
        <field length="999" num="56" type="LLLVAR" />
        <field length="999" num="57" type="LLLVAR" />
        <field length="999" num="58" type="LLLVAR" />
        <field length="999" num="59" type="LLLVAR" />
        <field length="999" num="60" type="LLLVAR" />
        <field length="999" num="61" type="LLLVAR" />
        <field length="999" num="62" type="LLLVAR" />
        <field length="999" num="63" type="LLLVAR" />
        <field length="64" num="64" type="ALPHA" />
        <field length="42" num="90" type="ALPHA" />
        <field length="42" num="95" type="ALPHA" />
        <field length="28" num="102" type="LLVAR" />
        <field length="28" num="103" type="LLVAR" />
        <field length="15" num="123" type="LLLVAR" />
        <field length="64" num="128" type="ALPHA" />
    </parse>

    <parse type="0430">
        <field length="19" num="2" type="LLVAR" />
        <field length="6" num="3" type="ALPHA" />
        <field length="12" num="4" type="ALPHA" />
        <field length="12" num="5" type="ALPHA" />
        <field length="12" num="6" type="ALPHA" />
        <field length="10" num="7" type="ALPHA" />
        <field length="8" num="8" type="ALPHA" />
        <field length="8" num="9" type="ALPHA" />
        <field length="8" num="10" type="ALPHA" />
        <field length="6" num="11" type="ALPHA" />
        <field length="6" num="12" type="ALPHA" />
        <field length="4" num="13" type="ALPHA" />
        <field length="4" num="14" type="ALPHA" />
        <field length="6" num="15" type="ALPHA" />
        <field length="4" num="16" type="ALPHA" />
        <field length="4" num="17" type="ALPHA" />
        <field length="4" num="18" type="ALPHA" />
        <field length="3" num="19" type="ALPHA" />
        <field length="3" num="20" type="ALPHA" />
        <field length="3" num="21" type="ALPHA" />
        <field length="3" num="22" type="ALPHA" />
        <field length="3" num="23" type="ALPHA" />
        <field length="3" num="24" type="ALPHA" />
        <field length="2" num="25" type="ALPHA" />
        <field length="2" num="26" type="ALPHA" />
        <field length="1" num="27" type="ALPHA" />
        <field length="9" num="28" type="ALPHA" />
        <field length="9" num="29" type="ALPHA" />
        <field length="9" num="30" type="ALPHA" />
        <field length="9" num="31" type="ALPHA" />
        <field length="11" num="32" type="LLVAR" />
        <field length="11" num="33" type="LLVAR" />
        <field length="28" num="34" type="LLVAR" />
        <field length="37" num="35" type="LLVAR" />
        <field length="104" num="36" type="LLLVAR" />
        <field length="12" num="37" type="ALPHA" />
        <field length="6" num="38" type="ALPHA" />
        <field length="2" num="39" type="ALPHA" />
        <field length="3" num="40" type="ALPHA" />
        <field length="8" num="41" type="ALPHA" />
        <field length="15" num="42" type="ALPHA" />
        <field length="40" num="43" type="ALPHA" />
        <field length="25" num="44" type="LLVAR" />
        <field length="76" num="45" type="LLVAR" />
        <field length="999" num="46" type="LLLVAR" />
        <field length="999" num="47" type="LLLVAR" />
        <field length="999" num="48" type="LLLVAR" />
        <field length="3" num="49" type="ALPHA" />
        <field length="3" num="50" type="ALPHA" />
        <field length="3" num="51" type="ALPHA" />
        <field length="16" num="52" type="ALPHA" />
        <field length="96" num="53" type="ALPHA" />
        <field length="120" num="54" type="LLLVAR" />
        <field length="999" num="55" type="LLLVAR" />
        <field length="999" num="56" type="LLLVAR" />
        <field length="999" num="57" type="LLLVAR" />
        <field length="999" num="58" type="LLLVAR" />
        <field length="999" num="59" type="LLLVAR" />
        <field length="999" num="60" type="LLLVAR" />
        <field length="999" num="61" type="LLLVAR" />
        <field length="999" num="62" type="LLLVAR" />
        <field length="999" num="63" type="LLLVAR" />
        <field length="64" num="64" type="ALPHA" />
        <field length="42" num="90" type="ALPHA" />
        <field length="42" num="95" type="ALPHA" />
        <field length="28" num="102" type="LLVAR" />
        <field length="28" num="103" type="LLVAR" />
        <field length="15" num="123" type="LLLVAR" />
        <field length="64" num="128" type="ALPHA" />
    </parse>

    <parse type="0800">
        <field length="19" num="2" type="LLVAR" />
        <field length="6" num="3" type="ALPHA" />
        <field length="12" num="4" type="ALPHA" />
        <field length="12" num="5" type="ALPHA" />
        <field length="12" num="6" type="ALPHA" />
        <field length="10" num="7" type="ALPHA" />
        <field length="8" num="8" type="ALPHA" />
        <field length="8" num="9" type="ALPHA" />
        <field length="8" num="10" type="ALPHA" />
        <field length="6" num="11" type="ALPHA" />
        <field length="6" num="12" type="ALPHA" />
        <field length="4" num="13" type="ALPHA" />
        <field length="4" num="14" type="ALPHA" />
        <field length="6" num="15" type="ALPHA" />
        <field length="4" num="16" type="ALPHA" />
        <field length="4" num="17" type="ALPHA" />
        <field length="4" num="18" type="ALPHA" />
        <field length="3" num="19" type="ALPHA" />
        <field length="3" num="20" type="ALPHA" />
        <field length="3" num="21" type="ALPHA" />
        <field length="3" num="22" type="ALPHA" />
        <field length="3" num="23" type="ALPHA" />
        <field length="3" num="24" type="ALPHA" />
        <field length="2" num="25" type="ALPHA" />
        <field length="2" num="26" type="ALPHA" />
        <field length="1" num="27" type="ALPHA" />
        <field length="9" num="28" type="ALPHA" />
        <field length="9" num="29" type="ALPHA" />
        <field length="9" num="30" type="ALPHA" />
        <field length="9" num="31" type="ALPHA" />
        <field length="11" num="32" type="LLVAR" />
        <field length="11" num="33" type="LLVAR" />
        <field length="28" num="34" type="LLVAR" />
        <field length="37" num="35" type="LLVAR" />
        <field length="104" num="36" type="LLLVAR" />
        <field length="12" num="37" type="ALPHA" />
        <field length="6" num="38" type="ALPHA" />
        <field length="2" num="39" type="ALPHA" />
        <field length="3" num="40" type="ALPHA" />
        <field length="8" num="41" type="ALPHA" />
        <field length="15" num="42" type="ALPHA" />
        <field length="40" num="43" type="ALPHA" />
        <field length="25" num="44" type="LLVAR" />
        <field length="76" num="45" type="LLVAR" />
        <field length="999" num="46" type="LLLVAR" />
        <field length="999" num="47" type="LLLVAR" />
        <field length="999" num="48" type="LLLVAR" />
        <field length="3" num="49" type="ALPHA" />
        <field length="3" num="50" type="ALPHA" />
        <field length="3" num="51" type="ALPHA" />
        <field length="16" num="52" type="ALPHA" />
        <field length="96" num="53" type="ALPHA" />
        <field length="120" num="54" type="LLLVAR" />
        <field length="999" num="55" type="LLLVAR" />
        <field length="999" num="56" type="LLLVAR" />
        <field length="999" num="57" type="LLLVAR" />